runtime: go116

instance_class: F1

env_variables:
  APP_ENV: $APP_ENV
  MONGO_URI: $MONGO_URI
  GCP_PROJECTID: $GCP_PROJECTID
  GCP_BUCKETNAME: $GCP_BUCKETNAME
  GCP_PREFIX: $GCP_PREFIX
  JWT_SECRET: $JWT_SECRET
  REDIS_ENDPOINT: $REDIS_ENDPOINT
  REDIS_PORT: $REDIS_PORT
  REDIS_DB_PASSWORD: $REDIS_DB_PASSWORD
  ALLOW_ORIGINS_ENDPOINT: $ALLOW_ORIGINS_ENDPOINT

handlers:
  - url: /stylesheets
    static_dir: stylesheets

  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$

  - url: /.*
    script: auto
