services:
  web:
    build: .
    image: nitad
    ports:
      - '3000:3000'
    environment:
      - APP_ENV=${APP_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - GCP_SERVICE_ACCOUNT=${GCP_SERVICE_ACCOUNT}
      - GCP_PROJECTID=${GCP_PROJECTID}
      - GCP_BUCKETNAME=${GCP_BUCKETNAME}
      - ALLOW_ORIGINS_ENDPOINT=${ALLOW_ORIGINS_ENDPOINT}
      - REDIS_ENDPOINT=${REDIS_ENDPOINT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_PASSWORD=${REDIS_DB_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
