version: "3.8"

services:
  frontend:
    build:
      context: ./nitad-frontend
    image: nitad-frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./nitad-backend
    image: nitad-backend
    ports:
      - "8080:8080"
    env_file:
      - ./nitad-backend/.env
  nginx:
    build:
      context: .
    ports:
      - "80:80"
